### ISSUE TITLE
IAM Role Support

### ISSUE THREAD

**Issue by i0rek** [sendgridlabs/go-kinesis#14]
Hello,

what do you think about IAM Role Support? I don't think it would be hard thing to do: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html. For us it would be extremely usefull since we do everything with IAM Roles instead of shipping credentials.

**Comment by amoghe** [comment]
+1 . @i0rek let me know if you aren't actively working on a patch, I could whip up a PR for this.

**Comment by i0rek** [comment]
@amoghe I am not working on it, feel free to take a stab at it! That would be great!

**Comment by amoghe** [comment]
Okay, so pulling the credentials from the IAM role associated with the instance is trivial. Here are my thoughts so far:

Attaching an IAM role to the instance results in keys being made available via the metadata server. These can be fetched when the ```kinesis.NewClient``` populates the ```Auth``` struct (by looking at the env, and maybe also querying the server).

The part that is tricky to handle (and the part that I'd *really* like to handle) is where the keys are rotated, the kinesis client should also have its creds auto-magically updated. To do this we could either:

1. setup a goroutine that periodically polls and updates the keys in the ```Auth``` object. I don't particularly like this approach.
2. ```kinesis.Client.Do()``` can be made to inspect the response (after every request it makes), check for auth errors and maybe update its ```Auth``` and retry (once).

Option 2 seems simpler, so I'm inclined towards that. Thoughts?

**Comment by i0rek** [comment]
When I thought about it I planned to do 1). Because as far as I know we even know when the token expires, right?!

**Comment by amoghe** [comment]
> When I thought about it I planned to do 1). Because as far as I know we even know when the token expires, right?!

You are correct (I had not done all my homework). So the question now is what do we do with the expiry time? Setup a goroutine that wakes up at/around that time to refresh them?

**Comment by le0pard** [comment]
> You are correct (I had not done all my homework). So the question now is what do we do with the expiry time? Setup a goroutine that wakes up at/around that time to refresh them?

You can check expiration time before each request and refresh if need to do this before request. No need to create goroutine.

**Comment by amoghe** [comment]
> You can check expiration time before each request and refresh if need to do this before request. No need to create goroutine.

Yes, we can perform the time comparison before every call to ```client.Do()```, I was suggesting using the goroutine so that we could leave that codepath alone (and avoid unneccesary computation on what is essentially a hot codepath), and have another one update the ```Auth``` object when the time is right. Thoughts?

**Comment by le0pard** [comment]
@amoghe the main problem, what goroutine is not controllable by developer and possible cases, where it is not need. Simple example: current implementation no need goroutine and still be used by many developers.

**Comment by amoghe** [comment]
Thats fine. I'm okay with implementing it either way. 

Just so that I understand the reasoning better - seems like you would prefer it if we did not spawn goroutines behind the scenes (esp since the user cannot "control" them) ?

**Comment by le0pard** [comment]
> Just so that I understand the reasoning better - seems like you would prefer it if we did not spawn goroutines behind the scenes (esp since the user cannot "control" them) ?

Yes, you are right!

**Comment by rubyphunk** [comment]
Hi guys,

I just stumbled across this thread as I was going to fork the repo to add the ability to pass in the IAM token. I wanted to go for a more explicit and simple approach by changing  (https://github.com/sendgridlabs/go-kinesis/blob/master/kinesis.go#L50)

    func New(access_key string, secret_key string, region Region) *Kinesis {

to

    func New(auth *Auth, region Region) *Kinesis {

To me this seems more flexible and explicit. Wdyt?

Regarding the token rotation, do you really think this should be handled by the kinesis library? It would include speaking to the metadata service as well, including error handling and so on. To me this does not seem to match the focus of the kinesis lib and might be done by a different lib even? It probably would make sense if long running poll/subscribe methods would be in place but as far as I can see there's not such thing involved here.

**Comment by le0pard** [comment]
> To me this seems more flexible and explicit. Wdyt?

Looks good, need to see implementation :)

> Regarding the token rotation, do you really think this should be handled by the kinesis library? It would include speaking to the metadata service as well, including error handling and so on. To me this does not seem to match the focus of the kinesis lib and might be done by a different lib even? It probably would make sense if long running poll/subscribe methods would be in place but as far as I can see there's not such thing involved here.

Maybe. I am not using such feature in AWS, what is why harder to me say the best way to solve this problem. We can split this stuff in separate pull request.

**Comment by amoghe** [comment]
Please review https://github.com/sendgridlabs/go-kinesis/pull/19

**Comment by amoghe** [comment]
@rubyphunk I think the first change you propose (to the signature of ```New```) is reasonable, and can be made regardless.

However the fetching of keys from the metadata server by the kinesis lib emulates the behavior of other aws/cloud libs which attempt to fetch keys from various sources (including env and reading dotfiles). For this reason I don't think its unreasonable for it do to do this. Also, if you see #19 , you will
notice that is preserves the current (annoying, IMHO) behavior of being silent when it fails to get creds.

**Comment by amoghe** [comment]
This (http://docs.aws.amazon.com/aws-sdk-php/guide/latest/credentials.html) documents all the ways one can plumb credentials to the SDK. The official AWS SDKs attempt to fetch credentials from various sources, for the ruby sdk (```aws-sdk```), the order of preference seems to be:

1. environment variables
2. dotfile (~/.aws/credentials)
3. metadata server (IAM credentials)

**Comment by amoghe** [comment]
@rubyphunk with your proposed change to the constructor, you can override this "magical" creds fetching by providing your own ```Auth``` object (with the ```Expiry``` set to the zero-value of ```time.Time{}```). This will give you the behavior you want, while allowing the lib to do more for other users. Thoughts?

**Comment by rubyphunk** [comment]
@amoghe Yes makes sense. Cool. Being able to turn of magic behavior is always a good idea :)
One small addition (I'll comment on the PR #19 in a sec): If you add the ```X-Amz-Security-Token``` regardless of the state of ```c.Auth.Expiry``` we would not even need to pass in an empty ```Expiry``` which makes stuff a little more predictable.

**Comment by rubyphunk** [comment]
@le0pard @amoghe See #20

**Comment by le0pard** [comment]
Closed by https://github.com/sendgridlabs/go-kinesis/pull/19

**Comment by i0rek** [comment]
Thank you very much for your work, this is great!
