### ISSUE TITLE
goamz 

### ISSUE THREAD

**Issue by Fodoj** [sendgridlabs/go-kinesis#22]
Any plans on eventually moving it to goamz? Using both goamz and go-kinesis in one project is a bit confusing at the moment. :walking:

**Comment by le0pard** [comment]
As I can see, them have kinesis: https://github.com/crowdmob/goamz/tree/master/kinesis

**Comment by Fodoj** [comment]
@le0pard ok now it's just super confusing, because this one also exists https://github.com/goamz/goamz :)

**Comment by le0pard** [comment]
@Fodoj I don't know how to help with this. This one is directly only to working with kinesis + have cli to work with it.

**Comment by Fodoj** [comment]
@le0pard ok, thanks a lot for pointing to other goamz. Do you have ETA of merge of https://github.com/sendgridlabs/go-kinesis/pull/19 ? :)

**Comment by le0pard** [comment]
@Fodoj hope will review after work today and merge or give some feedback.

**Comment by Fodoj** [comment]
@le0pard awesome, thanks again. Closing this issue
