### ISSUE TITLE
Unexpected EOF when using PutRecords

### ISSUE THREAD

**Issue by agokaiso** [sendgridlabs/go-kinesis#25]
Post https://kinesis.ap-southeast-1.amazonaws.com: EOF

Why?

**Comment by le0pard** [comment]
Does example also raise such error? https://github.com/sendgridlabs/go-kinesis/blob/master/examples/example.go

**Comment by agokaiso** [comment]
The examples is ok. But, It occasionally occur when using PutRecords. I do not quite understand the meaning of that. Whether the posted data have any questions?

**Comment by le0pard** [comment]
@agokaiso Did you checking size of PutRecords? By kinesis doc max size is 50 kilobytes.
