### ISSUE TITLE
Mock request to kinesis

### ISSUE THREAD

**Issue by Fodoj** [sendgridlabs/go-kinesis#26]
Any hint on how to mock requests to kinesis in tests?

Currently my test freezes for 30 seconds and then fails. :(

**Comment by le0pard** [comment]
Most simple way - create fake_kinesis server, which will work like real kinesis (like https://github.com/ananthakumaran/fake_dynamo).

**Comment by Fodoj** [comment]
I am not sure it's simplest. I tried to create dummy server and replace default transport, but it nearly impossible to find any information on it, except the fact that some people do that successfully :\

**Comment by dlsniper** [comment]
You could try to use this project: https://github.com/mhart/kinesalite
And a docker image that goes with it: https://registry.hub.docker.com/u/dlsniper/kinesalite

Hope this helps.

**Comment by le0pard** [comment]
We already using it for testing - https://github.com/sendgridlabs/go-kinesis/blob/master/.travis.yml
