### ISSUE TITLE
Example rate-limit issues

### ISSUE THREAD

**Issue by ItsLeeOwen** [sendgridlabs/go-kinesis#27]
Kinesis rate limits GetRecords requests to 5 per second per shard.  The example's "getRecords" method will quickly hit that, and by not handling the rate limit error will fail as you proceed to attempt iterating over the records.  It's recommended to sleep after every request for 500-1000ms, and to check for errors after GetRecords

http://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html
If a call returns 10 MB of data, subsequent calls made within the next 5 seconds throw ProvisionedThroughputExceededException. If there is insufficient provisioned throughput on the shard, subsequent calls made within the next 1 second throw ProvisionedThroughputExceededException. Note that GetRecords won't return any data when it throws an exception. For this reason, we recommend that you wait one second between calls to GetRecords; however, it's possible that the application will get exceptions for longer than 1 second

Python library calling sleep:
https://github.com/awslabs/kinesis-poster-worker/blob/master/worker.py

**Comment by le0pard** [comment]
Fixed by https://github.com/sendgridlabs/go-kinesis/pull/28
