### ISSUE TITLE
NewAuthFromEnv() does not support AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by strife25** [sendgridlabs/go-kinesis#45]
I found that `NewAuthFromEnv` does not support looking for the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` for API key values. This will cause problems for some users as the [AWS cli docs](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) does recommend setting those environment variables.

**Comment by le0pard** [comment]
It use another env variables - https://github.com/sendgridlabs/go-kinesis/blob/0e7b60986a8c32d83b4c84822d4f806247abaa42/auth.go#L15-L16 This doc for aws command line tool. If you need change its - make PR (but leave compatibility with old env variables) :)

**Comment by strife25** [comment]
Already working on it. :)

**Comment by strife25** [comment]
And the PR is up at #46.
