### ISSUE TITLE
Is there any examples for the batchProducer

### ISSUE THREAD

**Issue by grandmore** [sendgridlabs/go-kinesis#50]
A example would make it easier to understand how it should be used.

Any help would be gratefully received.

Thanks.

**Comment by le0pard** [comment]
Examples you can see in tests: https://github.com/sendgridlabs/go-kinesis/blob/master/batchproducer/batchproducer_test.go

**Comment by grandmore** [comment]
I have looked though the tests and they are helpful. But I am still a bit lost.

The test are using Mocks instead of the real BatchingKinesisClient.

For example:

`b, err := batchproducer.New(&BatchingKinesisClient{}, "foo", config)`

How do I create the BatchingKinesisClient so it can be passed in?

Thanks

**Comment by le0pard** [comment]
https://github.com/sendgridlabs/go-kinesis/blob/master/batchproducer/batchproducer.go#L65-L67 - all in code

**Comment by grandmore** [comment]
I just worked that out as your email landed. It's just an interface for the standard ksis client object. :-)

Sometimes I just can't see the wood for the trees.

Thanks.

**Comment by le0pard** [comment]
No problem.

**Comment by grandmore** [comment]
When I get a fully function batchProducer I will do a PR and write it up. There is a still a lot of considerations to go through yet.
