### ISSUE TITLE
Firehose integration

### ISSUE THREAD

**Issue by jadbox** [sendgridlabs/go-kinesis#55]
I see @fjordan may have a working solution:
https://github.com/rewardStyle/go-kinesis/commit/6c4ffb22a5b57cc05dcc8705465ea57c5de3c9de

Is this something that can be merged in?

**Comment by le0pard** [comment]
It depend not from me. If no PR - maybe it is not ready.

**Comment by fjordan** [comment]
@jadbox @le0pard it needs tests and I'm not sure when I will be able to add them. 
If you would like I can make a PR
