### ISSUE TITLE
Host check in Sign method doesn't work for local Kinesis

### ISSUE THREAD

**Issue by schickling** [sendgridlabs/go-kinesis#58]
[This host check in the `Sign` method](https://github.com/sendgridlabs/go-kinesis/blob/master/sign.go#L38) doesn't work when using a local Kinesis server such as Kinesalite.

**Comment by le0pard** [comment]
You can provide PR to fix this.

**Comment by schickling** [comment]
What would be a better check for the sign method?

**Comment by le0pard** [comment]
As using Kinesalite (it should have something to mock this)
