### ISSUE TITLE
Sample code keeps asking for AWS_SECURITY_TOKEN

### ISSUE THREAD

**Issue by alterx** [sendgridlabs/go-kinesis#61]
I'm trying to run the sample code provided in the examples folder but it just keeps asking for the AWS_SECURITY_TOKEN env variable.

According to the [Shared config file section](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/) in the AWS Go SDK "Credentials are the values the SDK should use for authenticating requests with AWS Services. They arfrom a configuration file will need to include both aws_access_key_id and aws_secret_access_key must be provided together in the same file to be considered valid. The values will be ignored if not a complete group. aws_session_token is an optional field that can be provided if both of the other two fields are also provided." 
As you can see, the token is supposed to be optional if you provide both the secret and access keys but this code https://github.com/sendgridlabs/go-kinesis/blob/master/auth.go#L78
tells me that, in go-kinesis, it's mandatory.

Why isn't AWS_SECURITY_TOKEN optional?
Am I missing something here?

Thanks in advance for any help

**Comment by recurser** [comment]
I'm having the same issue (`Unable to retrieve security token from AWS_SECURITY_TOKEN env variable`).
